name: CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * 6"

jobs:
    compile:
        name: Create deb package
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
          - name: Run the build process with Docker
            uses: addnab/docker-run-action@v3
            with:
                image: debian:testing
                options: -v ${{ github.workspace }}:/root -v /output:/output
                run: |
                    cd /root
                    apt update
                    apt install devscripts equivs build-essential wget -y
                    mk-build-deps --install
                    yes | debuild -us -uc -b
                    mkdir -p /output/
                    mv ../*.deb /output/

          - uses: "marvinpinto/action-automatic-releases@latest"
            with:
                repo_token: "${{ secrets.GITHUB_TOKEN }}"
                automatic_release_tag: "current"
                prerelease: false
                title: "Latest release"
                files: |
                  /output/*


